# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicnotes', '0003_auto_20190703_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songpart',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
