# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-04 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicnotes', '0004_auto_20190703_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='capo',
        ),
        migrations.AddField(
            model_name='instrumentpart',
            name='capo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
