# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicnotes', '0005_auto_20190704_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentpart',
            name='song_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicnotes.SongPart'),
        ),
        migrations.AlterField(
            model_name='songpart',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicnotes.Song'),
        ),
    ]
